service: michigan-api-resources

custom:
  table: 'Michigan_Upload'
provider:
  name: aws
  runtime: nodejs14.x
  stage: v2

resources:
  Resources:
    TableDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.table}
  Outputs:
    TableDynamoTableArn:
      Value:
        Fn::GetAtt:
          - TableDynamoDBTable
          - Arn
      Export:
        Name: MichiganApiUploadTableDynamoTableArn
    TableDynamoTableName:
      Value: ${self:custom.table}
      Export:
        Name: MichiganApiUploadTableDynamoTableName